apiVersion: apps/v1
kind: Deployment
metadata:
  name: video2gif-bot
  namespace: bots
spec:
  template:
    spec:
      containers:
        - name: video2gif-bot
          image: dima032398485/vid2gif_bot:latest
