apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - path: image-patch.yaml
    target:
      kind: Deployment
      name: video2gif-bot
      namespace: bots

images:
  - name: dima032398485/vid2gif_bot
    newTag: latest